version: '{build}'
shallow_clone: true

install:
  - ps: Install-Product node 8
  - set CI=true
  - set AVA_APPVEYOR=true
  - node --version
  - npm --version
  - npm install

build: off

test_script:
  - npm test
